import { StyleSheet } from "react-native";

const SignUpStyles = StyleSheet.create({
  container: {
    flex: 1,
    flexDirection: "row",
    backgroundColor: "#f2f2f2",
    justifyContent: "center", 
    alignItems: "center", 
  },
  // leftBox: {
  //   flex: 1,
  //   justifyContent: "center",
  //   alignItems: "center",
  //   padding: 10,
  //   marginTop: 20,
  //   marginBottom:50,
  //   marginLeft:10,
  //   marginRight:10,
  //   borderBottomLeftRadius: 20,
  //   borderBottomRightRadius: 20,
  //   shadowColor: "#000",
  //   shadowOpacity: 0.1,
  //   shadowRadius: 6,
  //   elevation: 7,
  // },
  welcome: {
    fontSize: 16,
    fontWeight: "600",
    color: "black",
    textAlign: "center",
    marginTop: 30,
    marginBottom: 10,
  },
  subText: {
    fontSize: 16,
    color: "white",
    textAlign: "center",
    marginBottom: 20,
  },
  loginButton: {
    // backgroundColor: "#4DBF99",
    borderWidth: 1,              // thickness of the border
    borderColor: "black",        // color of the border
    borderRadius: 10,  
    paddingVertical: 10,
    borderRadius: 8,
    alignItems: "center",
    marginTop: 10,
    marginBottom: 20,
    marginLeft:20,
    marginRight:20,
  },
  loginText: {
    color: "black",
    fontWeight: "bold",
    fontSize: 16,
  },
  rightBox: {
    flex: 1,
    backgroundColor: "white",
    justifyContent: "center",
    padding: 20,
    // borderTopLeftRadius: 20,
    borderRadius: 20,
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 4,
    width: "90%",
    // marginLeft: 5,
    // marginRight: 5,
    marginTop: 50,
    marginBottom: 50,
    maxWidth: 400,
    alignSelf: 'center',
  },
  startText: {
    fontSize: 18,
    fontWeight: "500",
    textAlign: "center",
    marginTop: 20,
  },
  createText: {
    fontSize: 22,
    fontWeight: "700",
    textAlign: "center",
    marginBottom: 20,
  },
  input: {
    borderWidth: 1,
    borderColor: "#ccc",
    borderRadius: 8,
    paddingHorizontal: 10,
    height: 50,
    marginBottom: 20,
    fontSize: 14,
  },
  error: {
    color: "red",
    textAlign: "center",
    marginBottom: 10,
  },
  signUpButton: {
    backgroundColor: "#4DBF99",
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: "center",
    marginTop: 10,
  },
  signUpText: {
    color: "white",
    fontWeight: "bold",
    fontSize: 16,
  },
});

export default SignUpStyles;
