import { StyleSheet, Dimensions, Platform } from "react-native";

const { width, height } = Dimensions.get("window");

export const createStyles = (theme) =>
  StyleSheet.create({
  container: {
      flex: 1,
      backgroundColor: '#490606ff',
      paddingBottom: 60, // niche tab navigator ke liye jagah
    }, 
  chatArea: {
    flex: 1,
    padding: 10,
    width: "55%",
    alignSelf: "center",
    backgroundColor: "transparent",
  },
  mode_container: {
        // borderWidth: 2,
        // borderColor: "#F59E0B",
        // alignContent: "right",
        position: "absolute",
        marginLeft: 1100,
        zIndex: 200,
        marginLeft: 1450,
        marginTop: 12,
    },
  messageBubble: {
    marginVertical: 5,
    padding: 10,
    borderRadius: 10,
    maxWidth: "80%",
  },
  userBubble: {
    alignSelf: "flex-end",
    backgroundColor: theme.userBubble, 
  },
  botBubble: {
    alignSelf: "flex-start",
    backgroundColor: theme.botBubble,
  },
  messageText: {
    fontSize: 16,
    color: "black",
  },
  fileContainer: {
    marginTop: 5,
    padding: 5,
    backgroundColor: "#ddd",
    borderRadius: 5,
  },
  fileLink: {
    color: "blue",
    textDecorationLine: "underline",
  },
  fileImage: {
    width: 120,
    height: 120,
    borderRadius: 8,
  },
  container: {
    flex: 1,
    height: height,
    width: width,
  },
  content: {
    flex: 1,
    alignItems: "center",
  },
  topbar: {
    width: "100%",
    height: 64,
    backgroundColor: theme.background,
    justifyContent: "center",
    alignItems: "flex-end",
    paddingRight: 10,
  },
  topbarButton: {
    height: 50,
    width: 100,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: theme.heading,
    borderRadius: 30,
    marginRight: 10,
  },
  bottomContainer: {
    width: "100%",
    borderColor: "#ddd",
    paddingBottom: 5,
    alignSelf: "center",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 20,
  },
  previewContainer: {
    flexDirection: "row",
    padding: 5,
    borderTopLeftRadius: 5,
    borderTopRightRadius: 5,
    maxHeight: 80,
  },
  fileBox: {
    marginRight: 8,
    position: "relative",
    backgroundColor: "#f1f1f1",
    padding: 5,
    borderRadius: 5,
    minWidth: 80,
    maxWidth: 120,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#ddd",
  },
  removeBtn: {
    position: "absolute",
    top: -5,
    right: -5,
    backgroundColor: "red",
    borderRadius: 10,
    paddingHorizontal: 5,
  },
  fileName: {
    fontSize: 12,
    color: "black",
  },
  dropdown:{
    height: 53,
    width: 170,
    paddingLeft: 5,
    // paddingRight: 10,
    // borderWidth: 10,
    borderRadius: 5,
    // marginLeft: 1,
    backgroundColor: theme.cardBackground,
    borderWidth:0, 
    fontSize: 18,
    marginLeft: 10,
    marginRight: 10,
   },
  search: {
    alignSelf: "center",
    width: "100%",
    justifyContent: "center",
    alignItems: "center",
  },
  inner: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    width: "95%",
    maxWidth: 1000,
    padding: 5,
    borderRadius: 10,
    marginLeft: 10,
  },
  textarea: {
    flex: 1,
    backgroundColor: theme.cardBackground,
    shadowColor: theme.shadowbackground,
    color: "black",
    paddingHorizontal: 10,
    paddingVertical: 6,
    // borderRadius: 5,
    fontSize: 16,
    lineHeight: 20,
    textAlignVertical: "top",
  },
  switch: {
    marginLeft: 5,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor:theme.heading,
    height: 55,
    width: 50,
    borderRadius: 5,
  },
  switchHovered: {
        ...Platform.select({
            web: {
                transform: [{ scale: 1.05 }],
                shadowColor: theme.shadowbackground,
                shadowOpacity: 0.4,
                shadowOffset: { width: 0, height: 8 },
                shadowRadius: 20,
                cursor: "pointer",
            },
        }),
    },
  add: {
    marginRight: -0,
    justifyContent: "center",
    alignItems: "center",
    height: 52,
    width: 40,
    backgroundColor: theme.heading,
    borderRadius: 0,
    borderTopLeftRadius: 5,
    borderBottomLeftRadius: 5,
  },
  below: {
    flex: 1,
    width: "100%",
    backgroundColor: "white",
  },
  hidden: {
    display: "none",
  },
});

export default createStyles;